[phases.setup]
nixPkgs = ['nodejs_18', 'python3', 'pkg-config', 'cairo', 'pango', 'libpng', 'jpeg', 'giflib', 'librsvg']

[phases.build]
cmds = [
  'npm ci',
  'npm run build'
]

[phases.start]
cmd = 'npm start'

[variables]
NODE_ENV = 'production'
NPM_CONFIG_PRODUCTION = 'false'